### ISSUE TITLE
sketch out a plan for the UI

### ISSUE THREAD

**Issue by nturley** [nturley/gullbog#9]
We'll be using the blueprintjs UI toolkit from palantir. Using ui components from the same toolkit where possible will allow us to have a consistent look and feel.

This is some of the ideas in my head but I'm not completely sold on any of them.

* Login/Welcome Screen
  * User enters name
  * User picks a color? icon? avatar?
  * Game title and a pretty image?
  * Version and changelog?
* the main boggle board that is displayed while the round is in progress.
  * Start/Cancel the round
  * Letter squares (user can enter words by typing, or dragging)
  * countdown timer
  * current list of words
  * in game chat? 
* Round Results
  * Words everyone tried and which were taken by other players. Maybe some kinda animation to reveal them one by one?
  * The score for the round and the score for the whole game so far. (Maybe put the scoring on a separate tab?)
  * In game chat

## Keep in Mind
* The UI must be mobile friendly. Many will be using this webpage from their phones.
* Accessibility: Color blind players should not be at a significant disadvantage

**Comment by josephscottwilliams** [comment]
![IMG_2707](https://user-images.githubusercontent.com/53028146/79526099-2242b400-802a-11ea-84fa-840a6788278b.jpg)

**Comment by josephscottwilliams** [comment]
Just a sketch of desktop version idea...let me know your thoughts. We can probably consolidate some of these by using some sort of tab feature as I don't think most stats on scorecard would be necessary for in-game play.

**Comment by nturley** [comment]
So this is my layout interpretation of your sketch. Only part I wasn't sure about was whether the timer belonged to the header up top or whether it belonged to the center column.

I organized it into containers that have horizontal children or vertical children. This is common in flexbox layouts, as opposed to a grid layout. Looks pretty straightforward.

![image](https://user-images.githubusercontent.com/2446659/79534454-44dfc780-8040-11ea-9a74-26005ed04f6a.png)

By default the page content flows downward, so we have a header element and a div for the body of the page. The body will have use a horizontal layout for it's children (flex, space between) to form the three columns. This means that the left and right columns will stay stuck to the edges of the screen (with a margin) and the middle column will be centered. All three columns will have a vertical layout and the button group will have a horizontal layout (flex, space around) so the buttons will evenly distribute themselves to the width of the middle column.

All three columns will probably be fixed width but if the page width gets too narrow, then we will probably collapse the left and possibly the right column so for mobile, they can just have the boggle board to fill the screen.

This looks pretty good.
